volumes:
  sparepal_local_postgres_data: {}
  sparepal_local_postgres_data_backups: {}
  local_certs: {}  # New volume for certificates
  local_media: {}  # New volume for media files

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sparepal_local_django
    container_name: sparepal_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      - local_media:/app/local-dev/media  # Mount media volume
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sparepal_production_postgres
    container_name: sparepal_local_postgres
    volumes:
      - sparepal_local_postgres_data:/var/lib/postgresql/data
      - sparepal_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres


  # Nginx for cert
  nginx-proxy:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs  # Mount certificates from local folder to Nginx
    restart: always
    depends_on:
      - django
