# Generated by Django 5.1.3 on 2024-11-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyDetailAddress',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='CompanyManagerDetail',
            new_name='Manager',
        ),
    ]
