# Generated by Django 5.1.3 on 2024-11-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_companydetailaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
