# Generated by Django 5.1.3 on 2024-11-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a supplier and can create a company or is                 simply a regular user.', verbose_name='supplier status'),
        ),
    ]
